local durationWeed = 90000
local durationOpium = 90000
local durationLean = 90000
local durationCocaine = 120000
local durationLsd = 90000


RegisterNetEvent("tofdrugs:effectcannabis")
AddEventHandler("tofdrugs:effectcannabis",function()
    SetPedIsDrunk(PlayerPedId(), true)
    RequestAnimSet("move_p_m_zero_slow") 
    while not HasAnimSetLoaded("move_p_m_zero_slow") do
      Citizen.Wait(0)
    end   
    TaskStartScenarioInPlace(PlayerPedId(), "WORLD_HUMAN_SMOKING_POT", 0, 1)
    Citizen.Wait(8000)
    DoScreenFadeOut(500)
    Citizen.Wait(500)
    ClearPedTasksImmediately(PlayerPedId())
    SetTimecycleModifier("spectator5")
    DoScreenFadeIn(500)
    Citizen.Wait(200) 
    SetPedMotionBlur(PlayerPedId(), true)
    SetPedMovementClipset(PlayerPedId(), "move_p_m_zero_slow", true)
    Citizen.Wait(durationWeed)
    endeffectsdrugs()
end)

RegisterNetEvent("tofdrugs:effectopium")
AddEventHandler("tofdrugs:effectopium",function()
    SetPedIsDrunk(PlayerPedId(), true)
    RequestAnimSet("move_p_m_zero_slow") 
    while not HasAnimSetLoaded("move_p_m_zero_slow") do
      Citizen.Wait(0)
    end   
    TaskStartScenarioInPlace(PlayerPedId(), "WORLD_HUMAN_SMOKING_POT", 0, 1)
    Citizen.Wait(8000)
    DoScreenFadeOut(500)
    Citizen.Wait(500)
    ClearPedTasksImmediately(PlayerPedId())
    SetTimecycleModifier("BeastIntro02")
    ShakeGameplayCam("FAMILY5_DRUG_TRIP_SHAKE", 1.5)
    DoScreenFadeIn(500)
    Citizen.Wait(200) 
    SetPedMotionBlur(PlayerPedId(), true)
    SetPedMovementClipset(PlayerPedId(), "move_p_m_zero_slow", true)
    Citizen.Wait(durationOpium)
    ShakeGameplayCam("FAMILY5_DRUG_TRIP_SHAKE", 0.0)
    endeffectsdrugs()
end)

RegisterNetEvent("tofdrugs:effectlean")
AddEventHandler("tofdrugs:effectlean",function()
    SetPedIsDrunk(PlayerPedId(), true)
    loadAnimDict("mp_player_intdrink")
    TaskPlayAnim(PlayerPedId(), "mp_player_intdrink", "loop_bottle", 8.0, 1.0, 8000, 49, 0, 0, 0, 0)
    Citizen.Wait(8000)
    RequestAnimSet("MOVE_M@DRUNK@VERYDRUNK")
    while not HasAnimSetLoaded("MOVE_M@DRUNK@VERYDRUNK") do
        Citizen.Wait(0)
    end
    DoScreenFadeOut(500)
    Citizen.Wait(500)
    DoScreenFadeIn(500)
    Citizen.Wait(200)
    SetPedMovementClipset(PlayerPedId(), "MOVE_M@DRUNK@VERYDRUNK", true)
    StartScreenEffect("DrugsMichaelAliensFight", 3.0, 0)
    AnimpostfxPlay("RampageOut", durationLean, true)
    Citizen.Wait(durationLean)
    DoScreenFadeOut(500)
    Citizen.Wait(500)
    AnimpostfxStop("RampageOut")
    ResetPedMovementClipset(PlayerPedId(), 0)
    DoScreenFadeIn(500)
    Citizen.Wait(200)
    StopScreenEffect("DrugsMichaelAliensFight")
end)

RegisterNetEvent("tofdrugs:effectcocaine")
AddEventHandler("tofdrugs:effectcocaine",function()
    SetPedIsDrunk(PlayerPedId(), true)
    loadAnimDict("anim@mp_player_intcelebrationmale@face_palm")
    TaskPlayAnim(PlayerPedId(), "anim@mp_player_intcelebrationmale@face_palm", "face_palm", 3.0, 3.0, 3000, 48, 0, false, false, false)
    Citizen.Wait(3000)
    RequestAnimSet("MOVE_M@QUICK")
    while not HasAnimSetLoaded("MOVE_M@QUICK") do
        Citizen.Wait(0)
    end
    DoScreenFadeOut(500)
    Citizen.Wait(500)
    DoScreenFadeIn(500)
    Citizen.Wait(200)
    SetPedMovementClipset(PlayerPedId(), "MOVE_M@QUICK", true)
    AnimpostfxPlay("DrugsDrivingIn", durationCocaine, true)
    AnimpostfxPlay("DMT_flight_intro", durationCocaine, true)
    Citizen.Wait(durationCocaine)
    DoScreenFadeOut(500)
    Citizen.Wait(500)
    AnimpostfxStop("DrugsDrivingIn")
    AnimpostfxStop("DMT_flight_intro")
    ResetPedMovementClipset(PlayerPedId(), 0)
    DoScreenFadeIn(500)
    Citizen.Wait(200)
end)

RegisterNetEvent("tofdrugs:effectlsd")
AddEventHandler("tofdrugs:effectlsd",function()
    SetPedIsDrunk(PlayerPedId(), true)
    loadAnimDict("mp_suicide")
    TaskPlayAnim(PlayerPedId(), "mp_suicide", "pill", 3.0, 3.0, 2000, 48, 0, false, false, false)
    Citizen.Wait(2000)
    RequestAnimSet("MOVE_M@DRUNK@VERYDRUNK")
    while not HasAnimSetLoaded("MOVE_M@DRUNK@VERYDRUNK") do
        Citizen.Wait(0)
    end
    DoScreenFadeOut(500)
    Citizen.Wait(500)
    DoScreenFadeIn(500)
    Citizen.Wait(200)
    SetPedMovementClipset(PlayerPedId(), "MOVE_M@DRUNK@VERYDRUNK", true)
    StartScreenEffect("DrugsMichaelAliensFight", 3.0, 0)
    AnimpostfxPlay("DRUG_gas_huffin", durationLsd, true)
    Citizen.Wait(durationLsd)
    DoScreenFadeOut(500)
    Citizen.Wait(500)
    AnimpostfxStop("DRUG_gas_huffin")
    ResetPedMovementClipset(PlayerPedId(), 0)
    DoScreenFadeIn(500)
    Citizen.Wait(200)
    StopScreenEffect("DrugsMichaelAliensFight")
end)

function endeffectsdrugs()
      ClearTimecycleModifier()
      ResetScenarioTypesEnabled()
      ResetPedMovementClipset(PlayerPedId(), 0)
      SetPedMotionBlur(PlayerPedId(), false)
      SetPedIsDrunk(PlayerPedId(), false)
end

function loadAnimDict(dict)
    while (not HasAnimDictLoaded(dict)) do
        RequestAnimDict(dict)
        Citizen.Wait(5)
    end
end 